---
webserver_port: 80
webserver_ssl_port: 443
webserver_worker_processes: auto
webserver_worker_connections: 1024

webserver_vhosts:
  - name: default
    server_name: "_"
    root: /var/www/html
    index: index.html
    ssl: false
